name: Publicar en npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar yarn
      run: npm install -g yarn

    - name: Instalar dependencias
      run: yarn

    - name: Iniciar sesión en npm
      run: npm login --registry=https://registry.npmjs.org/ --scope=@fone01

    - name: Publicar en npm
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
