name: Publicar en npm

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar yarn
      run: npm install -g yarn

    - name: Instalar dependencias
      run: yarn

    - name: Build
      run: yarn build

    - name: Configurar .npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc


    - name: Publicar en npm
      run: yarn publish
